const NODE_ENV = process.env.NODE_ENV;
const MONGO_URL = process.env.COFFEE_ESHOP_NO_ADMIN_MONGO_URL;
const API_PORT = process.env.COFFEE_ESHOP_NO_ADMIN_API_PORT;
const PROD_MEDIA = process.env.COFFEE_ESHOP_NO_ADMIN_PROD_MEDIA;
const STRIPE_SECRET = process.env.COFFEE_ESHOP_NO_ADMIN_STRIPE_SECRET;
const CLIENT_URL = process.env.COFFEE_ESHOP_NO_ADMIN_CLIENT_URL;

module.exports = {
  NODE_ENV,
  MONGO_URL,
  API_PORT,
  PROD_MEDIA,
  STRIPE_SECRET,
  CLIENT_URL,
};
